### ISSUE TITLE
阿里云等一些vps的IP获取问题

### ISSUE THREAD

**Issue by jinzizhe** [Ccapton/brook-web#14]
阿里云等一些vps的ifconfig里面显示的是内网IP并不是外网IP。
所以自动生成部署的时候似乎会把IP指定成外网IP。

**Comment by jinzizhe** [comment]
你好，修改之后启动服务报错了。
下面是报错信息：
[root@izj6c62mggaelp1108o8ygz brook-web]# python brook-web.py --port=8080
 * Serving Flask app "brook-web" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "brook-web.py", line 918, in <module>
    app.run(host='47.75.0.45', port=default_port, debug=debug)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 795, in run_simple
    s.bind(get_sockaddr(hostname, port, address_family))
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address

**Comment by Ccapton** [comment]
> 你好，修改之后启动服务报错了。
> 下面是报错信息：
> [root@izj6c62mggaelp1108o8ygz brook-web]# python brook-web.py --port=8080
> 
> * Serving Flask app "brook-web" (lazy loading)
> * Environment: production
>   WARNING: Do not use the development server in a production environment.
>   Use a production WSGI server instead.
> * Debug mode: on
>   Traceback (most recent call last):
>   File "brook-web.py", line 918, in 
>   app.run(host='47.75.0.45', port=default_port, debug=debug)
>   File "/usr/lib/python2.7/site-packages/flask/app.py", line 943, in run
>   run_simple(host, port, self, **options)
>   File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 795, in run_simple
>   s.bind(get_sockaddr(hostname, port, address_family))
>   File "/usr/lib64/python2.7/socket.py", line 224, in meth
>   return getattr(self._sock,name)(*args)
>   socket.error: [Errno 99] Cannot assign requested address

试一下 127.0.0.1 或者 0.0.0.0

**Comment by jinzizhe** [comment]
你好，感谢你的回复，把host=改成0.0.0.0有效，服务能正常启动。
在web界面仍然显示了内网IP，但是客户端输入公网IP能够连接。
非常感谢！

**Comment by Ccapton** [comment]
> 你好，感谢你的回复，把host=改成0.0.0.0有效，服务能正常启动。
> 在web界面仍然显示了内网IP，但是客户端输入公网IP能够连接。
> 非常感谢！

不客气，欢迎分享这个项目给你的朋友们

**Comment by changchun7** [comment]
怎么让Brook web显示谷歌云的外网IP

**Comment by caobaosir** [comment]
curl ipv4.icanhazip.com
仅供参考

**Comment by jxyk2007** [comment]
> 如果你有能力，你可以修改一下brook-web.py的最后一行代码,改为
> 
> app.run(host='你的内网ip', port=default_port, debug=debug)

手动设置host ip 无法启动进程

**Comment by jxyk2007** [comment]
把host=改成0.0.0.0有效 netstat 也看到tcp        0      0 0.0.0.0:5000            0.0.0.0:*               LISTEN 
但是还是无法访问，扫描5000端口是关闭的

**Comment by jxyk2007** [comment]
from urllib2 import urlopen
my_ip = urlopen('http://ipv4.icanhazip.com').read()
print my_ip
